In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv(r"D:\MachineLearning\MachineLearning_Intro\100-Days-ML-Code\Dataset\data.csv")

In [4]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,3].values

In [8]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [5]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Handling Missing Data

### SimpleImputer is imported from scikit-learn to handle missing values.

missing_values=np.nan: tells the imputer that np.nan marks missing entries.

strategy="mean": missing values will be replaced with the mean of the column.

X[:, 1:3] selects columns 1 and 2 (Python indexing is zero-based).

The imputer calculates the mean of each selected column, ignoring np.nan.

The imputer replaces all np.nan values in those columns with the computed column means.

The transformed values are written back into the original dataset X.

In [12]:
import numpy as np
from sklearn.impute import SimpleImputer

# Create the imputer to replace NaN with column mean
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

# Fit on columns 1 and 2
imputer = imputer.fit(X[:, 1:3])

# Transform and replace
X[:, 1:3] = imputer.transform(X[:, 1:3])


In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Step 4: Encoding categorical data

Importing encoders

LabelEncoder: Converts categorical labels (like "red", "blue", "green") into numeric codes (0, 1, 2).

OneHotEncoder: Converts categorical labels into binary vectors (e.g., "red" → [1,0,0], "blue" → [0,1,0]).

In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])

In [18]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

Creating a dummy variable

In [23]:
#onehotencoder = OneHotEncoder(categorical_features = [0])
# Apply OneHotEncoder only to column 0
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [0])],
    remainder='passthrough'   # keep other columns unchanged
)
X = ct.fit_transform(X).astype(int)

labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

In [24]:
X

array([[    0,     1,     0,     0,    44, 72000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     1,     0,    30, 54000],
       [    1,     0,     0,     1,    38, 61000],
       [    1,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    35, 58000],
       [    1,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    1,     0,     1,     0,    50, 83000],
       [    0,     1,     0,     0,    37, 67000]])

## Step 5: Splitting the datasets into training sets and Test sets

In [26]:
from sklearn.model_selection import train_test_split

# Split dataset into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=0
)


In [27]:
X_train

array([[    1,     0,     1,     0,    40, 63777],
       [    0,     1,     0,     0,    37, 67000],
       [    1,     0,     0,     1,    27, 48000],
       [    1,     0,     0,     1,    38, 52000],
       [    0,     1,     0,     0,    48, 79000],
       [    1,     0,     0,     1,    38, 61000],
       [    0,     1,     0,     0,    44, 72000],
       [    0,     1,     0,     0,    35, 58000]])

In [28]:
X_test

array([[    1,     0,     1,     0,    30, 54000],
       [    1,     0,     1,     0,    50, 83000]])

### Step 6: Feature Scaling


In [29]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)